// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    PageLayout: typeof import('./../src/layouts/page-layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiCard: typeof import('./../src/components/ui/ui-card.vue')['default']
    UiWindow: typeof import('./../src/components/ui/ui-window.vue')['default']
  }
}
